### ISSUE TITLE
Update Spring to 4.x

### ISSUE THREAD

**Issue by michael-o** [alexkasko/springjdbc-iterable#2]
The dependend Spring version is not supported anymore. Please align the source to Spring 4.x.

**Comment by alexkasko** [comment]
Hi,

On 01/19/2016 01:40 PM, Michael Osipov wrote:

> The dependend Spring version is not supported anymore. Please align the source to Spring 4.x.

Unfortunately I don't work with Spring anymore, if you'll like to 
maintain this library - please fork it and publish it to Maven central - 
I'll add the appropriate message and a link to your repo into the readme.

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/springjdbc-iterable/issues/2

## 

-Alex

**Comment by michael-o** [comment]
What a pity, this library is awesome. I think, it'd be best to add your code to Spring JDBC directly. I will reach out to Spring JIRA in a couple of days.

**Comment by michael-o** [comment]
Here is the Spring issue: https://jira.spring.io/browse/SPR-13900

**Comment by alexkasko** [comment]
On 01/28/2016 01:41 PM, Michael Osipov wrote:

> Here is the Spring issue: https://jira.spring.io/browse/SPR-13900

Thanks for that, it would be great if this code will be integrated into 
srping-jdbc. Please let me know if I'll need to sign some kind of 
contributor agreement.

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/springjdbc-iterable/issues/2#issuecomment-176189642

## 

-Alex

**Comment by michael-o** [comment]
This library worked flawlessly for at least 5 years on Spring 4.x w/o a single change. @alexkasko Спасибо тебе!
Since this does not work with Spring 5 it is now legacy. The Spring issue for the same approach has been solved and implemented as `Stream` with Java 8. Works like this one. I am now also able to stream hundreds of thousands of lines to the client. Closing this as overcome by events.
